# Generated by Django 3.2.11 on 2022-05-31 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_booktable_email_alter_booktable_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktable',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
    ]
